### ISSUE TITLE
Modernize CI

### ISSUE THREAD

**Issue by grst** [omnideconv/immunedeconv#100]
- [ ] use pre-commit CI with styler
- [ ] build artifact of gh-pages in PRs
- [ ] deploy gh-pages only when merging into master
- [ ] pre-commit for roxygenize (?)

EDIT: actually, the current way of deploying github pages is already quite smart. It deploys each PR in a subfolder as a preview. This has the limitation that this doesn't work for PRs from a fork, so I should switch to artifacts nonetheless

**Comment by grst** [comment]
@federicomarini, what checks do you usually include (apart from the usual R CMD CHECK and testthat)? 

In Python packages I now err on the side of having all kinds of automated code-style fixes and autoformatting as part of `pre-commit`. But I don't have such a good overview of the conventions in R packages.

**Comment by federicomarini** [comment]
I am doing "pretty standard stuff".

This would be
- R CMD check
- BiocCheck
- test automatically run in the check, but also some test coverage (via `covr`)
- autodeploy of the pkgdown website for the package

The linting is something I prefer to have more control "by hand" for. Just a matter of taste, probably.
I have seen that in place for bioconda recipes, but I would say that in that spot, that's reasonable.
Forcing too much on styling conventions might be a little "too invasive"?

**Comment by grst** [comment]
coverage is a good point! 

Everyone hates linting if it's just nitpicking about the code! I'm talking about automated fixes. Almost every Python project seems to have `black` nowadays and I love it, mostly because
 * It immediately ends all code style discussions
 * It guarantees minimal diffs, which is nice when reviewing PRs

Styler should work in a similar way.

**Comment by federicomarini** [comment]
I cannot un-agree more on the "unification" part, it is only that I am used to (co-)work also with other persons whose style is different and I had the impression some time that they feel a little _offended_ for having "a machine" telling how their code should be written.
That said: I am all in for this kind of "standardization". I still do these things by hand, and announce beforehand that "the codebase is getting a styler round" - this somehow simplifies the loop and reduce possible frictions 😉 
YMMV depending on whom you deal with  😄
