### ISSUE TITLE
Wrong names of ESTIMATE scores

### ISSUE THREAD

**Issue by FFinotello** [omnideconv/immunedeconv#128]
@LorenzoMerotto @constantin-zackl can we fix the names of the various ESTIMATE scores so they are equal to the original ones also when the `deconvolute` function is used? Thanks!

**Comment by LorenzoMerotto** [comment]
@constantin-zackl opened a pull request #127 where he updated the mapping sheet. However there is a problem with the tests, likely related to the libraries and not the edit on the names. I am still looking into it

**Comment by FFinotello** [comment]
Yes, totally agree. But the current mapping is wrong as the ESTIMATE score (which is the sum of the stromal and immune score) is remapped to tumor purity while, in fact, it should anticorrelate with it.

**Comment by grst** [comment]
ok, I see

**Comment by grst** [comment]
please don't forget to make a release after this is fixed. Bugfix -> increase last bit of the version number.

**Comment by grst** [comment]
@LorenzoMerotto, @czackl is this completed (including new version released?)

**Comment by LorenzoMerotto** [comment]
Fixed but no release yet
