### ISSUE TITLE
Hi what is the original article to BASE method for deconvolute_mouse()?

### ISSUE THREAD

**Issue by klai001** [omnideconv/immunedeconv#144]
It doesnt seem to be described anywhere.
I tried searching for it but i cant find the original article.
Just want to understand the theory behind this method.

Many thanks!

**Comment by LorenzoMerotto** [comment]
Hello @klai001 
This is the publication where BASE was introduced: https://www.nature.com/articles/ncomms10248#Sec23
You can find the detailed description of the method under the Methods, "Calculation of the CLS", [here](https://www.nature.com/articles/ncomms10248#Sec12)

In the GitHub [homepage](https://github.com/omnideconv/immunedeconv) of immunedeconv you can find the links to all the references
