### ISSUE TITLE
Error running cibersort

### ISSUE THREAD

**Issue by malonzm1** [omnideconv/immunedeconv#149]
Hi,

When I try running cibersort (with sample dataset), I get the following error:

> res <- deconvolute(gene_expression=immunedeconv::dataset_racle$expr_mat, method='cibersort')

>>> Running cibersort
Error in (function (sig_matrix, mixture_file, perm = 0, QN = TRUE)  :         
  unused arguments (absolute = FALSE, abs_method = "sig.score")

Please advise.

Thanks.

**Comment by malonzm1** [comment]
I checked similar issues and it might be because I'm using version 1.02? I got this from https://cibersortx.stanford.edu/csdownload.php. Where can I access the latest version?

**Comment by LorenzoMerotto** [comment]
As we discussed in the previous issues, it seems that the script compatible with immunedeconv is not available anymore.

**Comment by malonzm1** [comment]
Oh. Thanks.
