### ISSUE TITLE
Add CIBERSORTx Method

### ISSUE THREAD

**Issue by DarioS** [omnideconv/immunedeconv#30]
Could there be [CIBERSORTx](https://www.nature.com/articles/s41587-019-0114-2) also? It would be good to use the latest and greatest version of CIBERSORT.

**Comment by grst** [comment]
That's a great idea! 
I don't have capacity to implement that though. 
A pull request would be highly welcome! 

[Here](https://github.com/icbi-lab/immune_deconvolution_benchmark/#add-the-new-method-to-the-immunedeconv-package) is information on how to add a new tool.

**Comment by DarioS** [comment]
Thanks, I won't have any time to consider this until next year, so it depends who can get to it sooner.

**Comment by BairdMcI** [comment]
Hi there,

I was wondering if there was any update as to where it is possible to use CIBERSORT or CIBERSORTx yet? I know it's been a while, but from what I can see, the source code for CIBERSORTx is still not up, and I can no longer log into CIBERSORT to access the original source code. 
Thanks!

**Comment by grst** [comment]
We are currently working on a successor of immunedeconv that will provide access to single-cell based deconvolution tools, including CIBERSORTx. Stay tuned!

Even so, due to the licensing restrictions of CIBERSORTx, we will only be able to make it available as a wrapper - You will still need to obtain an access token from the CIBERSORT website.

**Comment by antonkulaga** [comment]
@grst, any estimates when it will be avaliable?

**Comment by grst** [comment]
We will certainly need a few more months to wrap it up.

**Comment by PelzKo** [comment]
Hey @quanc1989 We have finished almost everything internally (including the cibersortx wrapper), but it will probably still take some time until we can publish it or make it public.
BUT if you are interested to beta test it, just send me an email at konstantin.pelz@tum.de.

**Comment by quanc1989** [comment]
Thanks a lot  @PelzKo 
Looking forward to the new version.

**Comment by lincj1994** [comment]
Hi @grst. How about the cibersortx wrapper? Thanks.

**Comment by grst** [comment]
Happy to announce that the development version of [omnideconv](https://github.com/omnideconv/omnideconv) is now publicly available :tada: 

 It includes a wrapper for CIBERSORTx and many more methods working with single-cell data.
