### ISSUE TITLE
Documentation for mouse methods

### ISSUE THREAD

**Issue by grst** [omnideconv/immunedeconv#93]
@LorenzoMerotto added additional methods for mouse deconvolution. 

For them to be fully usable for end-users, we still need to make them available in the documentation: 

- [ ] Add methods to the "methods, licenses, citations" section in the readme
- [ ] Add methods to the list of available methods in "basic usage" (maybe highlight which are mouse and which are human)
- [ ] If there is anything special needed to make the method work ([like cibersort](https://icbi-lab.github.io/immunedeconv/articles/immunedeconv.html#special-case-cibersort) or TIMER) add such as section to the "Getting started" section. 
- [ ] Add to "interpretation of scores" in the getting started section
- [ ] Optional: Create a "mouse" vignette. @LorenzoMerotto, in case you have some simple benchmark or case-study for mouse data available, it might make sense to integrate it here. We could still add something later if it doesn't make sense outside the "omnideconv" context. 

Once these points are addressed, we can make a 2.1 release including the mouse methods.

**Comment by grst** [comment]
@LorenzoMerotto, do you think you could work on this? 

@FFinotello, what are your thoughts on the "mouse vignette"?

**Comment by FFinotello** [comment]
Thanks for putting this together, @grst. I agree with the full plan.
A very simple vignette should be easy to put together using the Petitprez dataset, provided that we give access to this data (see also the latest omnideconv issue).

**Comment by LorenzoMerotto** [comment]
Thanks Gregor for putting this list together. 
The first 4 points are quite straightforward, while for the last one we will see how we proceed for omnideconv.
